{{- if .Values.client.enabled }}
{{ $root := . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "stats-exporter.fullname" . }}-exporter-source
  labels:
    app: {{ template "stats-exporter.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: "kubernetes.io/storageos"
data:
  {{ range $path, $bytes := .Files.Glob "binary-logs/*" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
  {{ end }}
{{- end }}