{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stats-load-test.fullname" . }}-server
  labels:
    {{- include "stats-load-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "stats-load-test.selectorLabels" . | nindent 4 }}
{{- end }}